### ISSUE TITLE
Select Token Not necessary

### ISSUE THREAD

**Issue by saschakruesi** [wallee-payment/wallee-ios-sdk#10]
**Issues:**

No token is present the selection of select token navigation on top does not make sense. If no token is available it should be a back button to the app screen before payment process is initialized. 

![bildschirmfoto 2017-10-24 um 11 54 30](https://user-images.githubusercontent.com/22472999/31936877-28fd2fc8-b8b3-11e7-9b12-538d568e95df.png)

**Comment by schmidan** [comment]
resolved in #14
