### ISSUE TITLE
Scroll Bar in payment Form

### ISSUE THREAD

**Issue by saschakruesi** [wallee-payment/wallee-ios-sdk#16]
**Issue with Scroll Bar in Payment Form**

In case there are more information like invoice the scroll bar does not work. 
![bildschirmfoto 2017-11-15 um 15 59 18](https://user-images.githubusercontent.com/22472999/32842802-53b4ad1e-ca1e-11e7-9178-8658ed045254.png)

**Comment by schmidan** [comment]
can you clarify a little?  
tests with different devices and simulators all showed no problem scrolling.

**Comment by saschakruesi** [comment]
@schmidan Just use in Space 421 with the credentials the payment method invoice and you will see that you can not scroll to the fields below street. I sued for this the iphone8 plus simulator. If you want I can also show it to remotely?

Attached is also a screenshot what happens if you click into the street field. 


![bildschirmfoto 2017-11-17 um 18 56 18](https://user-images.githubusercontent.com/22472999/32961534-305134a8-cbc9-11e7-8908-5e2f652561ad.png)
