### ISSUE TITLE
Logo rendering Sofort Image

### ISSUE THREAD

**Issue by saschakruesi** [wallee-payment/wallee-ios-sdk#18]
Issue SVG Rendering of SOFORT IMAGES SVGS

The SVG for Sofort and others is not rendered correctly
![bildschirmfoto 2017-11-15 um 16 06 38](https://user-images.githubusercontent.com/22472999/32843061-0e043770-ca1f-11e7-81a0-3d413f218354.png)

**Comment by saschakruesi** [comment]
@schmidan The issue with Sofort and the rendering seems ok now. What still does not work you can not scroll on the web page - at least in the simulator. This is apparent when on the sofort page but can also be tested on the invoice processor (see screenshot below)

![bildschirmfoto 2017-11-24 um 12 52 18](https://user-images.githubusercontent.com/22472999/33209539-953ce4be-d116-11e7-89a3-6e8f0a7f0d80.png)

**Comment by schmidan** [comment]
closing this as this issue is resolved.  
i opened a new issue with your scrolling report #22
