### ISSUE TITLE
Forward with off-site payment methods

### ISSUE THREAD

**Issue by saschakruesi** [wallee-payment/wallee-ios-sdk#19]
**Issue forward the client automatically for Off-Site Payment Methods**

I added sofort for you to test a real offsite payment method. In this case the iframe is empty and the client should be automatically redirected to Sofort. At the moment you do have to click submit that this happens. 

I left it active in the space 412 for you to test. 
![bildschirmfoto 2017-11-15 um 16 05 28](https://user-images.githubusercontent.com/22472999/32843138-4453f7f2-ca1f-11e7-9880-3fc8686d5466.png)

**Comment by schmidan** [comment]
hei @saschakruesi the behaviour is changed and will be in the next release.  
just as a heads up, currently the frame is not empty since it is displaying the Test Data. As soon as this is gone, the form will be automatically submitted.

**Comment by saschakruesi** [comment]
fixed
