### ISSUE TITLE
Position Button Submit / Change Payment Method

### ISSUE THREAD

**Issue by saschakruesi** [wallee-payment/wallee-ios-sdk#9]
**Issues:**

On the payment page the position of the button to submit and change the payment method jumps or  overlaps the input fields (see screenshot attached).

![bildschirmfoto 2017-10-24 um 11 54 30](https://user-images.githubusercontent.com/22472999/31936577-4223c5bc-b8b2-11e7-9582-46efd188bfd6.png)

**Comment by schmidan** [comment]
this issue should be resolve in #15

**Comment by saschakruesi** [comment]
Issue is now fixed.
